/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nCDgC9KmIRm
 */


export function Component() {
  return (
    (<main className="flex-1 p-6">
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-xl font-bold mb-4">CPU Usage</h2>
          <div className="flex items-center space-x-2">
            <svg
              className=" h-6 w-6 text-gray-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg">
              <rect height="18" rx="2" width="18" x="3" y="3" />
              <path d="M11 9h4a2 2 0 0 0 2-2V3" />
              <circle cx="9" cy="9" r="2" />
              <path d="M7 21v-4a2 2 0 0 1 2-2h4" />
              <circle cx="15" cy="15" r="2" />
            </svg>
            <div className="text-gray-800 dark:text-white">75%</div>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-xl font-bold mb-4">Memory Usage</h2>
          <div className="flex items-center space-x-2">
            <svg
              className=" h-6 w-6 text-gray-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg">
              <path d="M6 19v-3" />
              <path d="M10 19v-3" />
              <path d="M14 19v-3" />
              <path d="M18 19v-3" />
              <path d="M8 11V9" />
              <path d="M16 11V9" />
              <path d="M12 11V9" />
              <path d="M2 15h20" />
              <path
                d="M2 7a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v1.1a2 2 0 0 0 0 3.837V17a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-5.1a2 2 0 0 0 0-3.837Z" />
            </svg>
            <div className="text-gray-800 dark:text-white">60%</div>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-xl font-bold mb-4">Health Check</h2>
          <div className="flex items-center space-x-2">
            <svg
              className=" h-6 w-6 text-green-500"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg">
              <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
              <polyline points="22 4 12 14.01 9 11.01" />
            </svg>
            <div className="text-gray-800 dark:text-white">Healthy</div>
          </div>
        </div>
      </div>
    </main>)
  );
}
