/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6vXq708FlJr
 */
import { Button } from "@/components/ui/button"
import { SelectTrigger, SelectItem, SelectGroup, SelectContent, Select } from "@/components/ui/select"
import Link from "next/link"

export function Home() {
  return (
    (<div className="flex flex-col h-screen bg-white dark:bg-gray-800">
      <nav
        className="flex items-center justify-between px-6 py-4 border-b shadow-lg">
        <div className="flex items-center space-x-5">
          <svg
            className=" h-7 w-7 text-blue-500"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg">
            <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
          </svg>
          <h1 className="text-2xl font-bold text-blue-500">Cloud Platform</h1>
        </div>
        <div className="relative">
          <svg
            className=" absolute left-3 top-2 h-6 w-6 text-gray-500"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg">
            <circle cx="11" cy="11" r="8" />
            <path d="m21 21-4.3-4.3" />
          </svg>
          <input
            className="pl-10 pr-5 rounded-md h-10 bg-gray-100 dark:bg-gray-700 focus:outline-none"
            placeholder="Search"
            type="text" />
        </div>
        <div className="flex items-center space-x-10">
          <Button className="rounded-full" size="icon" variant="ghost">
            <img
              alt="Profile"
              className="rounded-full"
              height="32"
              src="/placeholder.svg"
              style={{
                aspectRatio: "32/32",
                objectFit: "cover",
              }}
              width="32" />
          </Button>
          <div className="text-gray-800 dark:text-white">Username</div>
          <Select>
            <SelectTrigger>
              <svg
                className=" h-6 w-6 text-gray-500"
                fill="none"
                height="24"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth="2"
                viewBox="0 0 24 24"
                width="24"
                xmlns="http://www.w3.org/2000/svg">
                <line x1="4" x2="20" y1="12" y2="12" />
                <line x1="4" x2="20" y1="6" y2="6" />
                <line x1="4" x2="20" y1="18" y2="18" />
              </svg>
              <span className="sr-only">Open user menu</span>
            </SelectTrigger>
            <SelectContent>
              <SelectGroup>
                <SelectItem value="settings">Account Settings</SelectItem>
                <SelectItem value="notifications">Notifications</SelectItem>
                <SelectItem value="logout">Logout</SelectItem>
              </SelectGroup>
            </SelectContent>
          </Select>
        </div>
      </nav>
      <div className="flex flex-1 overflow-hidden">
        <aside className="w-64 bg-gray-100 dark:bg-gray-700 p-6">
          <nav>
            <Link
              className="block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-500 hover:text-white"
              href="#">
              Dashboard
            </Link>
            <Link
              className="block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-500 hover:text-white"
              href="#">
              Projects
            </Link>
            <Link
              className="block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-500 hover:text-white"
              href="#">
              Teams
            </Link>
            <Link
              className="block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-500 hover:text-white"
              href="#">
              Billing
            </Link>
            <Link
              className="block py-2.5 px-4 rounded transition duration-200 hover:bg-blue-500 hover:text-white"
              href="#">
              Settings
            </Link>
          </nav>
        </aside>
        <main className="flex-1 p-6">
          <div className="bg-white rounded-lg shadow p-6">
            <h2 className="text-xl font-bold mb-4">Welcome to Dashboard</h2>
          </div>
        </main>
      </div>
    </div>)
  );
}
